version: '3.8'

services:
  master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: master
    environment:
      - ROLE=master
    networks:
      - integration_network
    command: ["./master"]
    ports:
      - "12233:12233"

  worker1:
    depends_on:
      - master
    build:
      context: .
      dockerfile: Dockerfile
    container_name: worker1
    environment:
      - ROLE=worker
    networks:
      - integration_network
    command: ["./worker"]

  worker2:
    depends_on:
      - worker1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: worker2
    environment:
      - ROLE=worker
    networks:
      - integration_network
    command: ["./worker"]

  worker3:
    depends_on:
      - worker2
    build:
      context: .
      dockerfile: Dockerfile
    container_name: worker3
    environment:
      - ROLE=worker
    networks:
      - integration_network
    command: ["./worker"]

networks:
  integration_network:
    driver: bridge
